In [1]:
import torch

d:\Software\Python\Python39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x = torch.empty(2,3) #2D
print(x)
x = torch.empty(3,2,3) #3D
print(x)

tensor([[1.0647e+24, 2.8231e+23, 2.7252e+20],
        [2.6331e+20, 2.9172e+32, 1.8465e+25]])
tensor([[[2.6483e-30, 8.5199e-43, 2.6483e-30],
         [8.5199e-43, 2.6495e-30, 8.5199e-43]],

        [[2.6495e-30, 8.5199e-43, 2.7533e-30],
         [8.5199e-43, 2.7533e-30, 8.5199e-43]],

        [[2.7983e-30, 8.5199e-43, 2.7983e-30],
         [8.5199e-43, 2.7969e-30, 8.5199e-43]]])


In [3]:
x = torch.rand(2,2)
x

tensor([[0.5865, 0.0977],
        [0.1363, 0.2484]])

In [4]:
x = torch.zeros(2,2)
print(x)
torch.ones(2,2)

tensor([[0., 0.],
        [0., 0.]])


tensor([[1., 1.],
        [1., 1.]])

In [5]:
a = torch.ones(2,2,dtype=torch.int64)
a

tensor([[1, 1],
        [1, 1]])

In [6]:
a.size()

torch.Size([2, 2])

In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x+y # elt-wise addition
print(z)
print(torch.add(x,y))
y.add_(x)

tensor([[0.7331, 0.3299],
        [0.8434, 0.9587]])
tensor([[0.1596, 0.8263],
        [0.1818, 0.0091]])
tensor([[0.8927, 1.1561],
        [1.0252, 0.9678]])
tensor([[0.8927, 1.1561],
        [1.0252, 0.9678]])


tensor([[0.8927, 1.1561],
        [1.0252, 0.9678]])

In [8]:
z = x-y
print(z)
print(torch.sub(x,y))
print(x.sub_(y))

tensor([[-0.1596, -0.8263],
        [-0.1818, -0.0091]])
tensor([[-0.1596, -0.8263],
        [-0.1818, -0.0091]])
tensor([[-0.1596, -0.8263],
        [-0.1818, -0.0091]])


In [9]:
x = torch.rand(5,3)
print(x)
print(x[:,0])
print(x[1,:])
print(x[1,1])
print(x[1,1].item())

tensor([[0.5385, 0.7412, 0.7181],
        [0.9319, 0.3600, 0.5300],
        [0.3178, 0.5406, 0.2506],
        [0.4703, 0.7394, 0.9739],
        [0.8801, 0.4458, 0.6060]])
tensor([0.5385, 0.9319, 0.3178, 0.4703, 0.8801])
tensor([0.9319, 0.3600, 0.5300])
tensor(0.3600)
0.36001068353652954


In [10]:
x= torch.rand(4,4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1,8) # if we give -1, pytorch will automatically set the right size
print(z)

tensor([[0.5047, 0.3086, 0.4698, 0.7293],
        [0.2339, 0.3650, 0.0155, 0.3900],
        [0.6969, 0.8538, 0.1781, 0.1227],
        [0.4908, 0.9424, 0.5665, 0.9583]])
tensor([0.5047, 0.3086, 0.4698, 0.7293, 0.2339, 0.3650, 0.0155, 0.3900, 0.6969,
        0.8538, 0.1781, 0.1227, 0.4908, 0.9424, 0.5665, 0.9583])
tensor([[0.5047, 0.3086, 0.4698, 0.7293, 0.2339, 0.3650, 0.0155, 0.3900],
        [0.6969, 0.8538, 0.1781, 0.1227, 0.4908, 0.9424, 0.5665, 0.9583]])


In [11]:
import numpy as np

In [12]:
# Tensor to numpy array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1)
print(a,b)  # a and b point to the same memory location (mutable)

# Numpy to Tensor
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
a += 1
print(a,b)  # a and b point to the same memory location (mutable)

# a an b point to same memory location only in CPU, NOT in GPU

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [13]:
if torch.cuda.is_available():
    print("yes")
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y
    z = z.to("cpu")
    print(z)


yes
tensor([2., 2., 2., 2., 2.])


In [14]:
torch.cuda.is_available()

True