In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad=True) # randn - values from -1 to 1
x

tensor([ 0.0261, -1.1026, -0.8904], requires_grad=True)

In [3]:
y = x + 2
y # AddBackward refers to gradient func for backpropagation which is done later

tensor([2.0261, 0.8974, 1.1096], grad_fn=<AddBackward0>)

In [4]:
z = y*y*2   # MulBackward is the gradient func
z = z.mean() # MeanBackward 
z

tensor(4.0944, grad_fn=<MeanBackward0>)

In [5]:
# To calc gradient - Uses jacobian matrix
z.backward()  # dz/dx
x.grad # attribute which stores the gradient

tensor([2.7014, 1.1966, 1.4794])

Gradients for non-scalar ouputs:

In [6]:
# GRadient is only for scalars outputs, hence we give a vector
z = y*y*2
z
v = torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
z.backward(v)
x.grad

tensor([3.5119, 4.7863, 1.4839])

To Prevent tracking of the gradient functions: 
Eg: AddBackward, MulBackward, etc

In [7]:
a = torch.randn(3, requires_grad=True)
print(a)
# to remove gradient
a.requires_grad_(False)
print(a)

b = torch.randn(3, requires_grad=True)
print(b)
# to remove gradient
b = b.detach()
print(b)

c = torch.randn(3, requires_grad=True)
print(c)
# Remove gradient
with torch.no_grad():
    d = c+2
    print(d)

tensor([-0.1388,  0.2173,  0.2086], requires_grad=True)
tensor([-0.1388,  0.2173,  0.2086])
tensor([-0.6757,  1.5364, -0.5599], requires_grad=True)
tensor([-0.6757,  1.5364, -0.5599])
tensor([ 0.7040, -0.6361,  0.4905], requires_grad=True)
tensor([2.7040, 1.3639, 2.4905])


NOTE: Value of gradients in attribute "grad" gets summed, everytime we calc the gradient. Hence we need to clear it. To do so, we use {var}.grad.zero_()